name: Request GPU Test Label

permissions:
  pull-requests: write
  issues: write
  contents: read

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  comment-if-missing-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Detect changes in LLM blueprint directories
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --name-only origin/${{ github.base_ref }} HEAD | grep -E '^examples/(deepseed|torchtune)/'; then
            echo "found_changes=true" >> $GITHUB_OUTPUT
          else
            echo "found_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for ok-to-test-gpu-runner label
        id: label-check
        uses: actions/github-script@v7
        with:
          script: |
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const hasLabel = labels.some(l => l.name === 'ok-to-test-gpu-runner');
            core.setOutput('has_label', hasLabel ? 'true' : 'false');

      - name: Post comment requesting label
        if: steps.changes.outputs.found_changes == 'true' && steps.label-check.outputs.has_label == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Hello @andreyvelich @varodrig @jaiakash 👋,
              Changes were detected in the LLM blueprint directories (\`examples/deepseed\` or \`examples/torchtune\`).
              To run on GPU infra, please add the **ok-to-test-gpu-runner** label to this PR.`
                          });
