name: Approve to run E2E Tests on GPU Runner

permissions:
  actions: write
  contents: read

on:
  pull_request_target:
    types:
      - labeled
      - synchronize
  issue_comment:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  run-e2e-on-gpu-runner:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-on-gpu-runner') || github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Check if author is a Kubeflow GitHub member
        id: membership-check
        uses: actions/github-script@v7
        with:
          script: |
            const username = context.payload.pull_request.user.login;
            const org = context.repo.owner;
            try {
              await github.rest.orgs.checkMembershipForUser({ org, username });
              console.log(`User ${username} is a member of the ${org} organization.`);
              core.setOutput("is_member", "true");
            } catch (error) {
              if (error.status === 404) {
                console.log(`User ${username} is NOT a member of the ${org} organization.`);
                core.setOutput("is_member", "false");
              } else {
                throw error;
              }
            }

  gpu-job:
    needs: run-e2e-on-gpu-runner
    runs-on: self-hosted
    if: needs.run-e2e-on-gpu-runner.outputs.is_member == 'true' || contains(github.event.pull_request.labels.*.name, 'run-e2e-on-gpu-runner')
    steps:
      - uses: actions/checkout@v4
      - run: echo "✅ Running on OKE self-hosted GPU runner."
