name: Run GPU Job if Label Present

on:
  pull_request_target:
    types:
      - labeled
      - synchronize

jobs:
  gpu-job:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-on-gpu-runner')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo "✅ Running on OKE self-hosted GPU runner."
