name: Approve to run E2E Tests on GPU Runner

permissions:
  actions: write
  contents: read

on:
  pull_request_target:
    types:
      - labeled
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  run-e2e-on-gpu-runner:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-on-gpu-runner') || github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Check if author is a Kubeflow GitHub member
        id: membership-check
        uses: actions/github-script@v7
        with:
          script: |
            const username = context.payload.pull_request.user.login;
            const org = context.repo.owner;
            try {
              const res = await github.rest.orgs.checkMembershipForUser({
                org,
                username
              });
              core.setOutput("is_member", true);
            } catch (error) {
              if (error.status === 404) {
                // User is not a member
                core.setOutput("is_member", false);
              } else {
                throw error;
              }
            }
      
  trigger-gpu-self-runner:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request != null &&
      github.event.comment.user.login == 'jaiakash' &&
      contains(github.event.comment.body, '/run-e2e-on-gpu-runner')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo "✅ Running on OKE self-hosted runner triggered by @jaiakash."